### PR TITLE
fix soa err

### PR DESCRIPTION
**Pull request by yumusb**
fix soa err

### CODE REVIEW

**Comment by edmondas** [comment]
@yumusb Would you be able to describe briefly what it attempts to resolve?

**Comment by yumusb** [comment]
When add a new domain, for some reasons, the content of the SOA record is empty (when using the domain name template), then powerdns will return an error. Adding this code will solve the problem.

**Comment by edmondas** [comment]
@yumusb The changes you have made do not seem to solve the issue you are experiencing, since that method only runs when the template is changed.

Regardless, your code can be written differently:
```php
                            if ($soa_rec) {
                                $content = self::get_updated_soa_record($soa_rec);
                            } else {
                                $content = ZoneTemplate::parse_template_value($r["content"], $domain);
                            }
```

**Comment by yumusb** [comment]
PHP is a weakly typed language. In order to prevent future bugs, a complete judgment needs to be made, that is, == ""

**Comment by yumusb** [comment]
when i query the domain's soa record by phpmyadmin, i found the record is null, so i write this code.

**Comment by edmondas** [comment]
> PHP is a weakly typed language. In order to prevent future bugs, a complete judgment needs to be made, that is, == ""

OK, I was able to reproduce the problem. In general, it works as a failover and sets a default value. Aside from that, PHP has types, and I'm adding them where I can. Thanks.

**Pull request merged**
