### PR TITLE
adding new icons

### PR DESCRIPTION
**Pull request by bnchdan**
Also,
Can we add new icons?
image
image

### CODE REVIEW

**Comment by edmondas** [comment]
@bnchdan it would be better to reuse existing icons from top navigation. Other ideas:
- for list supermasters boxes or hdd-rack
- for logs activity or simply list (like in top menu)
- add super master hdd-network?
- bulk registration collection

There may be better associative images, but I hope you get the idea.

**Comment by edmondas** [comment]
I am merging this since I need to do other related refactorings.

**Comment by edmondas** [comment]
Updated icons and color of buttons:

image

**Comment by bnchdan** [comment]
> Updated icons and color of buttons:
> 
> image

It looks great and is more intuitive.

**Pull request merged**
