### PR TITLE
WIP: Expanded install instructions.

### PR DESCRIPTION
**Pull request by DaanSelen**
Hi there,

I would love to see if you think this is clearer. I managed to get it working with these instructions I used. Without knowing PHP.

Because as mentioned previously, review my changes in documentation carefully.

### CODE REVIEW

**Comment by DaanSelen** [comment]
I also am more a Debian developer. So the Fedora configuration should work... but I have not been able to verify yet. Debian works.

**Comment by edmondas** [comment]
@DaanSelen What's your plan? Should I merge it and fix those minor issues, or should I wait?

**Comment by DaanSelen** [comment]
> @DaanSelen What's your plan? Should I merge it and fix those minor issues, or should I wait?

I still need to look at your review. Sorry!

**Review by edmondas — APPROVED** [review]

**Comment by edmondas** [comment]
Thanks for your contribution! I'll merge your changes and make minor adjustments based on my comments while preparing for the release.

**Comment by DaanSelen** [comment]
> Thanks for your contribution! I'll merge your changes and make minor adjustments based on my comments while preparing for the release.

Thank you edmondas. Extreme apologies for not following up. I'll look if they are still working (on Debian and Fedora).

**Pull request merged**
